# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Page Title
email: your_email@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Copyright © 2016. All rights reserved.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://bongnv.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  bongnv

# Build settings
markdown: kramdown

# settings for generated permalinks
permalink: /:year/:month/:title.html

#category namme here
live_categories:
  enabled:
    - jekyll
    - update
  titles:
    jekyll: Category Title For Jekyll
    update: Category Title For Update